name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}

      - name: Build and Push Docker image for /host
        run: |
          docker build -t jernejofic444/host-microfrontend -f host/Dockerfile ./host
          docker push jernejofic444/host-microfrontend

      - name: Build and Push Docker image for /discounts
        run: |
          docker build -t jernejofic444/discounts-microfrontend -f discounts/Dockerfile ./discounts
          docker push jernejofic444/discounts-microfrontend

      - name: Build and Push Docker image for /notifications
        run: |
          docker build -t jernejofic444/notifications-microfrontend -f notifications/Dockerfile ./notifications
          docker push jernejofic444/notifications-microfrontend

      - name: Build and Push Docker image for /products
        run: |
          docker build -t jernejofic444/products-microfrontend -f products/Dockerfile ./products
          docker push jernejofic444/products-microfrontend
